"""add_reset_codes_table

Revision ID: ffc19567268f
Revises: 0bb75ac2fa31
Create Date: 2025-10-19 14:35:54.184256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ffc19567268f'
down_revision: Union[str, Sequence[str], None] = '0bb75ac2fa31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_codes',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_codes_code'), 'reset_codes', ['code'], unique=True)
    op.create_index(op.f('ix_reset_codes_id'), 'reset_codes', ['id'], unique=False)
    op.create_index(op.f('ix_reset_codes_user_id'), 'reset_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_codes_user_id'), table_name='reset_codes')
    op.drop_index(op.f('ix_reset_codes_id'), table_name='reset_codes')
    op.drop_index(op.f('ix_reset_codes_code'), table_name='reset_codes')
    op.drop_table('reset_codes')
    # ### end Alembic commands ###
